### ISSUE TITLE
Rigify Generate button missing (Blender v 2.77)

### ISSUE THREAD

**Issue by rrumfelt** [cessen/rigify#10]
I rigged my object in Blender 2.77 but when I try to generate, the button is missing.  It doesn't appear in Object mode or any other mode.  Please help asap.  Thanks!

![image](https://cloud.githubusercontent.com/assets/18460930/14524588/c5fb32ce-01fe-11e6-98d1-b03bc7201cd0.png)

**Comment by rrumfelt** [comment]
Anyone?

**Comment by rrumfelt** [comment]
Frustrating to have your rig ready to render but have no Rigify Generate button, and no one seems to know the fix?  Surely others have encountered this using v 2.77?

**Comment by cessen** [comment]
Judging by the screenshot, I don't see any other signs that Rigify is even enabled.  None of the other panels are showing up either.

Are you sure it's enabled?
