### ISSUE TITLE
Rigify error upon generation

### ISSUE THREAD

**Issue by Knuckl3head** [cessen/rigify#12]
Every time I try to generate this rig, an error pops up about not being able to find the key "hips." I am using Blender 2.77A with the script provided in Blender. I have Python Autorun enabled.

In Blender
![1](https://cloud.githubusercontent.com/assets/13644638/15417439/368766f4-1e13-11e6-9e00-f3296f52b037.png)

In Blender Console
![2](https://cloud.githubusercontent.com/assets/13644638/15417448/46fee5ca-1e13-11e6-812b-c4f8553d333d.png)

I read that the issue may be caused my a misnamed or improperly parented bone, here is the bone in the editor:
![3](https://cloud.githubusercontent.com/assets/13644638/15417463/60bf3ca8-1e13-11e6-8ea8-ca5dc338b2ce.png)

**Comment by cessen** [comment]
Thanks for the report!  Can you include the blend file that's causing the error?  That will make it much easier to debug.

I'm fairly busy right now, but I'll look into it the next chance I get.  My guess is this is a missing custom error message, where it should be telling you how the rig is misconfigured.  Should (hopefully) be an easy fix once I have the blend file.

**Comment by adapmal** [comment]
Same error here! Plus: If you delete the bone with the in the error message (The very "hips" in my case too), and you press "generate", the error will return with the above bone ("Spine"). Then, delete the Spine, error with "Chest"... and so on.

**Comment by adapmal** [comment]
JUST REALISED! The error only occurs if you're not on layer ONE. Moved my model from layer 3 to 1, and there were many armature replicas... (as many as the times I pressed "generate"). Deleted all replicas, pressed "generate" and boom!

**Comment by Knuckl3head** [comment]
Oh, that makes sense. I've been trying to recreate the error with no avail.
Thanks for your help.
