### ISSUE TITLE
rigify not generating control rigs correctly

### ISSUE THREAD

**Issue by JiahuiCai** [cessen/rigify#13]
![image](https://cloud.githubusercontent.com/assets/16479286/16697383/66b7f674-4517-11e6-9cef-aed449da0441.png)

here is a series of actions I have done, if I remembered correctly, :(

[obj mode]---create the meta-rig, scale up,apply L,R,S [edit mode]------ move joints around, change the roll properties of bones slightly, delete all the palm bones [obj mode]----- click on the generate button.

But somehow I can't reproduce the error, it only happened once.

I can create any rig I want with rigify now, but I am just curious why this happened.

Thank you! And I love this addon!

[rigify generation issue.zip](https://github.com/cessen/rigify/files/355174/rigify.generation.issue.zip)

**Comment by cessen** [comment]
Thanks for your report!  And sorry for the extremely late response.  I'm no longer maintaining Rigify, and the official version is part of the Blender addons repo.  You can report bugs there.
