### ISSUE TITLE
Shift + C & Random Line Glitches

### ISSUE THREAD

**Issue by rudytheguy** [cessen/rigify#14]
When using rigify, Shift + C makes all of the objects in the scene disappear and the mouse scroll functions not work correctly.  I also am seeing random lines jetting out of the upper arm of my bipedal humanoid mesh when in the armature's edit mode.  There are also lines jetting out of the knees and elbows when in object mode and when in pose mode.

Here are the screenshots of the random lines.

![screenshot 16](https://cloud.githubusercontent.com/assets/26914719/24687205/19269302-197e-11e7-8a72-35d88bfafb5d.png)

![screenshot 17](https://cloud.githubusercontent.com/assets/26914719/24687213/2bf68f14-197e-11e7-9bd0-8b8909713716.png)

![screenshot 18](https://cloud.githubusercontent.com/assets/26914719/24687215/2f73ce54-197e-11e7-8368-108704308b48.png)

**Comment by cessen** [comment]
I can't seem to reproduce this at all.  Are you sure this is a Rigify problem?  It seems more likely to be a Blender bug.

Also, I'm no longer maintaining Rigify, and the official version is part of the Blender addons repo.  So please report bugs there.
