### ISSUE TITLE
generated pitchipoy is offset and doesnt function!

### ISSUE THREAD

**Issue by dionyroxys** [cessen/rigify#15]
i dedcided to use your rig and after an entire day of setting it up , using pitchipoy's youtube video on it for some reason it generated the rig way to far back and became unfunctional , i followed the video as best as digitally possible , this rig has not only caused me great stress but it has also made me very angry on account of it taking so long for nothing

**Comment by dionyroxys** [comment]
![image](https://cloud.githubusercontent.com/assets/22668796/25025086/d1c223f8-206e-11e7-9a86-a1762c3bc90a.png)

**Comment by dionyroxys** [comment]
here is what it looks like , i have highlighted the rig to see it easier

**Comment by cessen** [comment]
Thanks for the screenshot!

Without access to your blend file it's hard to say for sure what's going on.  However, it does appear that your metarig does not have its transforms cleared, which Rigify assumes when generating the rig.  Make sure the metarig has location <0,0,0>, cleared rotation, and scale <1,1,1> before attempting to generate.

Also, I'm no longer maintaining Rigify, and the official version is part of the Blender addons repo.  So please report bugs there.  Apparently the version bundled with Blender hasn't had its "Report a bug" link updated yet, for which I apologize.  I'll ask them to change that.

**Comment by cessen** [comment]
Closing because there hasn't been activity in a while.
