### ISSUE TITLE
Can ya throw me a bone with a name

### ISSUE THREAD

**Issue by kelgit287** [cessen/rigify#16]
line 184 in execute
boneName = bpy.active_pose_bone.name

Attribute error: "noneType" object has not attribute name
 
everything is named don't know why it is giving me this

**Comment by cessen** [comment]
Hi, I'm actually no longer maintaining this add-on.  Development and maintenance have been taken over by some people working directly in the official Blender add-ons repo.  Please report bugs there.  Thanks!
