### ISSUE TITLE
Rigify shows version 0.4 while documentation show 0.5

### ISSUE THREAD

**Issue by schroef** [cessen/rigify#17]
OSX 10.11.6
Blender 2.78c

I just updated blender to 2.78c but im not seeing rigify 0.5 but still see 0.4 When looking at the documentation i see info about version 0.5

**Comment by cessen** [comment]
Hi schroef,
I believe this has been fixed in 2.79.

Also, I'm actually no longer the maintainer of Rigify. Development and maintenance have been taken over by some people working directly in the official Blender add-ons repo. Please report bugs there. Thanks!
