### ISSUE TITLE
Rig Missing

### ISSUE THREAD

**Issue by Xephos049** [cessen/rigify#5]
So I enabled the Rigify option in the User Preference in Addons and when I hit "Human (Meta-Rig)", It gives a small statement about context is incorrect and location unknown. Can I redownload the addon?

**Comment by cessen** [comment]
Sorry for the extremely late response.  Can you give me the exact text of the error message you're receiving?  It might help me track down the issue.

**Comment by Xephos049** [comment]
I... do not remember. XD This is a year ago so I have no clue what this is about.

**Comment by cessen** [comment]
Closing, as this is very old and the original reporter can't repro.
