### ISSUE TITLE
Rigging: Rigify

### ISSUE THREAD

**Issue by Mariolos76** [cessen/rigify#6]
Hello there,

I'm trying to rig my humanoid character in blender 2.7 to animate my character.
I saw some tutorial more than once but no one help! So i wish you help me, I followed
this tutorial " http://vimeo.com/30073532 " to rig my character, i followed very carefully
but i facing problem, when i finished putting the bones on my character .. I have to do the
following (( In Object mode, click on the character mesh & the bones > then press CTRL + P > then chose " With Automatic Weights " )) I did all of that, but when i click on With Automatic Weights some members separated from the body i don't know why! I capture my issue see the picture in this link http://www.photobox.co.uk/my/photo/full?photo_id=8325987210

**Comment by cessen** [comment]
Closing as this is really old.  But for future reference, auto-weighting is not a feature of Rigify, it's a separate built-in feature of Blender.  It's not totally clear to me that this was necessarily an auto-weighting bug, but if it was then it needs to be reported on the Blender bug tracker.
